{% set version = "1.3.340" %}
{% set sha256 = "b5c8550f567fbaf27306bfbda826b50dc044df61c0dfe17ab12af42baebad5e1" %}
{% set build_number = 0 %}
{% set deno_version = load_file_regex(load_file='configuration', regex_pattern='export\sDENO=v(\S+)') %}
{% set deno_dom_version = load_file_regex(load_file='configuration', regex_pattern='export DENO_DOM=v([^-]+)') %}
{% set pandoc_version = load_file_regex(load_file='configuration', regex_pattern='export PANDOC=(\S+)') %}

package:
  name: quarto
  version: {{ version }}

source:
  url: https://github.com/quarto-dev/quarto-cli/releases/download/v{{ version }}/quarto-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-look-for-tinytex-in-conda-bin-paths-when-CONDA_PREFI.patch
    - 0001-win-conda-path-overrides.patch
    - 0001-add-external-installer-command-for-packagers-like-co.patch
    - 0001-log-deno-bundle-command.patch
    - 0001-remove-QUARTO_VERSION-from-configuration.patch

build:
  number: {{ build_number }}

requirements:
  build:
    - deno      {{ deno_version.group(1) if deno_version else "" }}
    - deno-dom  {{ deno_dom_version.group(1) if deno_dom_version else "" }}
    - esbuild
    - pandoc    {{ pandoc_version.group(1) if deno_dom_version else "" }}
  run:
    # Deno, deno-dom and pandoc have proven to be fickle
    #    regarding Quarto's source code. The pinning here
    #    is not so much that there are binary compatibility
    #    issues, but just that these dependencies are only
    #    known to work in a pretty narrow range.
    - {{ pin_compatible("deno", max_pin="x.x.x") }}
    - {{ pin_compatible("pandoc", max_pin="x.x.x") }}
    # we vendor deno-dom JS dependencies, so it is important
    #  that the version at runtime matches the one at build time
    - {{ pin_compatible("deno-dom", max_pin="x.x.x") }}
    - esbuild
    - dart-sass

test:
  commands:
    - quarto check
    - "[ \"$(quarto --version)\" = \"{{ version }}\" ] || (echo \"Version set incorrectly\" && exit 1)"  # [unix]
    # it would be nice to do a version check on windows too, but I don't have a win machine and don't want to debug on CI
    - quarto render hello.qmd --to html
  files:
    - hello.qmd
  requires:
    - jupyter
    - python >=3
    - r-base >=4

about:
  home: https://quarto.org/
  license: GPL-2.0-or-later
  license_file:
    - COPYRIGHT
    - COPYING.md
  summary: An open-source scientific and technical publishing system built on Pandoc

extra:
  recipe-maintainers:
    - cderv
    - cscheid
    - dragonstyle
    - mfisher87
    - msarahan
