{% set version = "1.7.33" %}
{% set sha256 = "46a09dfc6e7c3da14898e4c25a21a2fa469d9690adb71471fd265e2d674282a1" %}
{% set build_number = 0 %}
{% set deno_version = load_file_regex(load_file='configuration', regex_pattern='export\sDENO=v(\S+)') %}
{% set deno_dom_version = load_file_regex(load_file='configuration', regex_pattern='export DENO_DOM=v([^-]+)') %}
{% set pandoc_version = load_file_regex(load_file='configuration', regex_pattern='export PANDOC=(\S+)') %}
{% set typst_version = load_file_regex(load_file='configuration', regex_pattern='export TYPST=(\S+)') %}

package:
  name: quarto
  version: {{ version }}

source:
  url: https://github.com/quarto-dev/quarto-cli/releases/download/v{{ version }}/quarto-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/0001-win-conda-path-overrides.patch
    - patches/0001-log-deno-bundle-command.patch
    - patches/0001-remove-QUARTO_VERSION-from-configuration.patch
    - patches/0001-always-build-quarto-preview-js.patch

build:
  number: {{ build_number }}

requirements:
  build:
    - deno      {{ deno_version.group(1) if deno_version else "" }}
    - deno-dom  {{ deno_dom_version.group(1) if deno_dom_version else "" }}
    - esbuild
    - pandoc {{ "==" ~ pandoc_version.group(1) if pandoc_version else "" }}
    - typst {{ "==" ~ typst_version.group(1) if typst_version else "" }}
  run:
    # Deno, deno-dom and pandoc have proven to be fickle
    #    regarding Quarto's source code. The pinning here
    #    is not so much that there are binary compatibility
    #    issues, but just that these dependencies are only
    #    known to work in a pretty narrow range.
    - {{ pin_compatible("deno", max_pin="x.x.x") }}
    # we vendor deno-dom JS dependencies, so it is important
    #  that the version at runtime matches the one at build time
    - {{ pin_compatible("deno-dom", max_pin="x.x.x") }}
    - pandoc {{ "==" ~ pandoc_version.group(1) if pandoc_version else "" }}
    - typst {{ "==" ~ typst_version.group(1) if typst_version else "" }}
    - esbuild
    - dart-sass

test:
  commands:
    - quarto check
    - "[ \"$(quarto --version)\" = \"{{ version }}\" ] || (echo \"Version set incorrectly\" && exit 1)"  # [unix]
    # it would be nice to do a version check on windows too, but I don't have a win machine and don't want to debug on CI
    - quarto render hello.qmd --to html
    - test -e "${QUARTO_SHARE_PATH}/preview/quarto-preview.js"  # [unix]
  files:
    - hello.qmd
  requires:
    - jupyter
    - python >=3
    - r-base >=4

about:
  home: https://quarto.org/
  license: MIT
  license_file:
    - COPYRIGHT
    - COPYING.md
  summary: An open-source scientific and technical publishing system built on Pandoc

extra:
  recipe-maintainers:
    - SaravananSathyanandhaQC
    - cderv
    - cscheid
    - dragonstyle
    - mfisher87
    - msarahan
