{% set version = "1.1.163" %}

package:
  name: quarto
  version: {{ version }}

source:
  url: https://github.com/quarto-dev/quarto-cli/releases/download/v1.1.163/quarto-1.1.163-win.zip

build:
  number: 0
  skip: True    # [not win]

test:
  commands:
    - quarto check
  requires:
    - python >=3
    - jupyter
    - r-base >=4

about:
  home: https://quarto.org/
  license: GPL-2.0-or-later
  license_file:
    - COPYRIGHT
    - COPYING.md
  summary: An open-source scientific and technical publishing system built on Pandoc

extra:
  recipe-maintainers:
    - msarahan
